version: '3.1'

services:
    softfocus-postgis:
        image: postgis/postgis
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: softfocus
            POSTGRES_DB: softfocus
            POSTGRES_PASSWORD: softfocus
        volumes:
            - ./database:/var/lib/mysql
